---
name: Build and Deploy 

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      
      - name: "Setup Node.js"
        uses: actions/setup-nodejs@v1
        with:
          node-version: "12.x"

      - name: npm install
        run: npm install --production